name: Ansible CI

on:
  workflow_dispatch: # leave this here so other repos can run manually
  workflow_call:
    inputs:
      scenario:
        required: false
        type: string
        default: default
      ansible_version:
        required: false
        type: string
        default: '5.2.0'
      ansible_lint_version:
        required: false
        type: string
        default: '5.3.2'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install CI deps
        run: |
          pip3 install \
            ansible==${{ inputs.ansible_version }}\
            ansible-lint==${{ inputs.ansible_lint_version }}\
            docker \
            molecule[docker]

      - name: Run tests
        run: molecule test -s ${{ inputs.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
