name: terrascan
on:
  workflow_call:
    inputs:
      directory:
        required: false
        type: string
        default: ${{ github.workspace }}

jobs:
  terrascan:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

      # https://github.com/marketplace/actions/terrascan-iac-scanner
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'azure'
        only_warn: true
        verbose: true
        sarif_upload: true
        #non_recursive:
        iac_dir: ${{ inputs.directory }}
        #policy_path:
        #skip_rules:
        #config_path:
        #find_vulnerabilities:

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif
