name: terratest
on:
  workflow_call:

jobs:
  terratest:
    runs-on: ubuntu-latest
    name: terratest-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Dependencies
      working-directory: test
      run: go mod init test && go mod tidy -compat=1.17

    - name: Test
      working-directory: test
      run: go test -v
