name: Terraform Module Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  TERRAFORM_VERSION: '1.1.6'
  TFLINT_VERSION: 'v0.34.1'

jobs:
  tflint:
    uses: ./.github/workflows/tflint.yml@main

  terrascan:
    uses: ./.github/workflows/terrascan.yml@main
    with:
      directory: '/examples/build'
    needs: tflint
    if: success()

  checkov:
    uses: ./.github/workflows/checkov.yml@main
    with:
      directory: '/examples/build'
    needs: tflint
    if: success()

  terratest:
    uses: ./.github/workflows/terratest.yml@main
    needs: tflint
    if: success()

  tag:
    uses: ./.github/workflows/github-release.yml@main
    needs:
      - terratest
      - checkov
    if: success()
