name: Terraform Module Build
on:
  workflow_call:

env:
  TERRAFORM_VERSION: '1.1.6'
  TFLINT_VERSION: 'v0.34.1'

jobs:
  tflint:
    uses: ./.github/workflows/tflint.yml

  terrascan:
    uses: ./.github/workflows/terrascan.yml
    with:
      directory: '/examples/build'
    needs: tflint
    if: success()

  checkov:
    uses: ./.github/workflows/checkov.yml
    with:
      directory: '/examples/build'
    needs: tflint
    if: success()

  terratest:
    uses: ./.github/workflows/terratest.yml
    needs: tflint
    if: success()

  tag:
    uses: ./.github/workflows/github-release.yml
    needs:
      - terratest
      - checkov
    if: success()
